### PR TITLE
Resolved Bug 990 : Design System > Components > Admin Dashboard > Button text alignment issue

### LINKED ISSUE #990: Design System > Components > Admin Dashboard > Button text alignment issue.
**Describe the bug**
Button text alignment issue.

**Steps to reproduce bug**
1. Go to 'https://dev-react.raaghu.ai/ & https://stage-react.raaghu.ai/'
2. Navigate to 'Design System > Components > Admin Dashboard >Default'

**Actual result-**
Button text alignment issue.

**Screenshots**
image

**Expected result-**
Button text alignment should be proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

### PR DESCRIPTION
**Pull request by nitinsonawane123**
1. Component admin dashboard button text alignment issue

## Screenshots :
 
image

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
alignment change please verify  with old version
image
image

**Comment by nitinsonawane123** [comment]
Resolved issue on PR https://github.com/Wai-Technologies/raaghu-react/pull/1031

**Comment by nitinsonawane123** [comment]
Resolved issue on PR https://github.com/Wai-Technologies/raaghu-react/pull/1031

**Comment by hemalatagaikwad** [comment]
already resolved

**Pull request closed without merging**
