### PR TITLE
Resolved Bug 172, 434, 654 and 658 : Missing required validation message and save button disable based on required field

### LINKED ISSUE #172: Storybook > Component > Account > Default > Captcha > Issues on Account component Small, Large mobile view captcha not visible.

### LINKED ISSUE #434: Storybook > Components >Identity Client Basic > Default > When Small & large Mobile label is sticking inputbox
**Describe the bug**
When Small & large Mobile label is sticking input box
Label and placeholder are not matching

**To Reproduce**
1. Go to 'Components'
Click on 'Identity Client Basic'
Click on 'Default'

**Screenshots**
image.
image

**Desktop (please complete the following information):**
 -OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information): NA**

**Additional context**

### LINKED ISSUE #654: Storybook >Component > Assistance >Default > Email> Required error is not display.
**Describe the bug**
Required error is not display.

**Steps to reproduce bug**
1.Go to 'https://stage-react.raaghu.ai/'
2. Navigate to 'Storybook >Component> Assistance >Default > Email'
3.  Enter email and remove required error is not display. 

**Actual result-**
Required error is not display.

**Screenshots**
image

**Expected result-**
Email is required.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

### LINKED ISSUE #658: Storybook >Components >Developer Mode > Default > Radio button, placeholder and validation issue.
**Describe the bug**
1. Radio already selected.
2. Placeholder issue.
3. Required error is not display.
4. Application Grant Type field after submitting not clear. 

**Steps to reproduce bug**
1.Go to 'https://stage-react.raaghu.ai/?path=/story/components-developer-mode--default'
2. Navigate to 'Storybook >Components >Developer Mode > Default'

**Actual result-**
1. Radio already selected.
2. Placeholder issue.
3. Required error is not display.
4. Application Grant Type field after submitting not clear.

**Screenshots**
image

image

**Expected result-**
1. Radio should be unselected.
2. Placeholder should be proper.
3. Required error should be display.
4. Application Grant Type field after submitting should be clear.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

### PR DESCRIPTION
**Pull request by poojagurav21**
## Description
1. Account- Required validation msg missing
2. Assistance- Email Validation message missing 
3. Developer mode- Required validation msg missing
4. Identity Client Basic - Required validation msg missing
5. For All the four component -save button disabled if required fields are empty

## Screenshots:
Developer mode
Assistance
Account
Identity client basic

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Ketan-Khalate** [comment]
@poojagurav21  I ran locally branch while checking I found issue on rds-comp-developer-mode component where if I am filling the all required fields then also Submit button is disable please look into it

cc : - @trivenikulkarni  @rameshwarkamandar @kaushikgokhale

**Comment by poojagurav21** [comment]
@Ketan-Khalate Issue resolved for rds-developer-mode.

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
Bug: 658 -Place holder font color does not correct 
image

**Comment by poojagurav21** [comment]
@hemalatagaikwad Issue resolved and changes pushed to the branch

**Review by hemalatagaikwad — APPROVED** [review]
ok

**Pull request merged**
