### PR TITLE
Completed Task 775 : Design System > Elements > Enhancements in Toggle

### LINKED ISSUE #775: Design System > Elements > Enhancements in Toggle
Design System > Elements > Enhancements in Toggle
Docs	1]  Toggles development different than design
Default	2]  4 layouts needs to be implemented
	3] 6 styles of toggles needs to be implemented
https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu-Design-System?node-id=1601-2723&node-type=frame&t=ncBHc3XyPjDjE2We-0

### PR DESCRIPTION
**Pull request by rahulp34**
## Description
Design System > Elements > Enhancements in Toggle
- Added 6 styles to toggle system and added disabled state styles also.

image
image
image
image
image
image
image

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
Current branch created from stage, so create new branch from dev and add changes needed

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
not working
image

**Comment by rahulp34** [comment]
image

errors removed, working fine

some curly brackets are missed out at the time of merging from developers, so when merged this branch got that error and now it is resolved

**Review by hemalatagaikwad — APPROVED** [review]
review and approve

**Pull request merged**
