### PR TITLE
Resolved bug 1065 : Components > Contact Us > Default > Send message button alignment issue

### LINKED ISSUE #1065: Design System > Components > Contact Us > Default > Send message button alignment issue
**Describe the bug**
1. Contact Us > Default > Send message button alignment issue.
2. Menu > Default > Horizontal line is display.

**Steps to reproduce bug**
1. Go to 'https://stage-react.raaghu.ai/?path=/story/components-contact-us--default'
2. Navigate to 'Design System > Components > Contact Us > Default '

**Actual result-**
1. Contact Us > Default > Send message button alignment issue.
2. Menu > Default > Horizontal line is display.

**Screenshots**
image

image

**Expected result-**
1. Contact Us > Default > Send message button alignment should be proper.
2. Menu > Default > Remove horizontal line.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

### PR DESCRIPTION
**Pull request by nitinsonawane123**
1. Resolved issue on Contact Us > Default > Send message button alignment.
2. Resolved issue on Menu > Default > Horizontal line is display.

## Screenshots :
 
image
image

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by poojagurav21 — CHANGES_REQUESTED** [review]
Resolved Conflicts
image

**Comment by nitinsonawane123** [comment]
Resolved Conflict

**Review by poojagurav21 — CHANGES_REQUESTED** [review]
Check the button alignment
image

**Comment by nitinsonawane123** [comment]
Resolved issue on button alignment.
image

**Review by poojagurav21 — CHANGES_REQUESTED** [review]
Error in Menu
image

**Comment by nitinsonawane123** [comment]
Menu page issue is resolved.
image

**Review by poojagurav21 — APPROVED** [review]

**Pull request merged**
