### PR TITLE
Completed Task 647 and Resolved Bug 756 : Design System Enhancements in Dropdown Element and Dropdown : Minor Issues 

### LINKED ISSUE #647: Design System > Enhancements in dropdown element
Design System > Enhancements in dropdown element

Create new element with name "User Dropdown" which allows
1.To select value with checkbox
2.To select value with text
3.To select value with li
4.Add user icon/avatar in user dropdown

Image

Image
Image

### LINKED ISSUE #756: Design System > Elements > Dropdown : Minor Issues
Design System > Elements > Dropdown : Minor Issues
Docs	1] Dropdown development different than design
Default	2] cheveron design need to change
	3] dropdown with icon
	4] dropdown with checkbox

### PR DESCRIPTION
**Pull request by prakashmhaske**
-  **Select List**

## Screenshots :
 
image

image

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
label props not working for default story
image

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
Please resolved conflicts

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
Please resolved conflicts

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
remove background color of selected items

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
label changes are not reflected
image

**Comment by nitinsonawane123** [comment]
Fixed Label Changes issue:

image
image

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
Please resolved build issue
image

**Comment by nitinsonawane123** [comment]
Resolved build issue.
image

**Review by poojagurav21 — APPROVED** [review]

**Review by poojagurav21 — APPROVED** [review]

**Review by hemalatagaikwad — APPROVED** [review]
review and approve

**Pull request merged**
