### PR TITLE
 Completed Task 784 : Design System > Elements > Enhancements in Action Button/Dropdown

### LINKED ISSUE #784: Design System > Elements > Enhancements in Action Button/Dropdown
Design System > Elements > Enhancements in Action Button/Dropdown
Docs	1] Action Button development different than design
	2] Please compare the colors which is required for element

Image
Image

### PR DESCRIPTION
**Pull request by prakashmhaske**
-  **Dropdown**
> Make the changes to raaghu-elements/src/rds-dropdown/rds-dropdown.stories.tsx ,raaghu-elements/src/rds-dropdown/rds-dropdown.tsx  file.
## Screenshots :
 
image

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
small is not working
image
please recheck all props

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
not working as expected

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
for small not display as required
image

**Comment by poojagurav21** [comment]
image
image
image

**Review by hemalatagaikwad — APPROVED** [review]
review and approve

**Pull request merged**
