### PR TITLE
Completed Task 820 : Design System > Elements > Enhancements in Side Navigation

### LINKED ISSUE #820: Design System > Elements > Side navigation enhancements
Design System > Elements > Side navigation enhancements as per the figma design

### PR DESCRIPTION
**Pull request by DeepashriDatar**
## Description

> Added new properties to match the wireframe 
> Added 3 stories Side Navigation, Side Navigation With List, Side Navigation Right

## ScreenShot 
1. Side Navigation (Collapse):
image

2. Side Navigation (Expanded):
image

3. Side Navigation With List (Collapse, With Profile)
image
  
4. Side Navigation With List (Expanded, With Profile)
image

6. Side Navigation With List (Collapse, Without Profile)
image

7. Side Navigation With List (Expanded, Without Profile)
image

8. Side Navigation Right (With Profile)
image
  
9. Side Navigation Right (Without Profile)
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
check responsiveness for small and Larger mobile
image

**Comment by DeepashriDatar** [comment]
css changes required for Mobile view, so assigning to @rahulp34

**Comment by rahulp34** [comment]
changes are completed and PR raised
https://github.com/Wai-Technologies/raaghu-react/pull/961

**Comment by hemalatagaikwad** [comment]
create new pr https://github.com/Wai-Technologies/raaghu-react/pull/961

**Pull request closed without merging**
