### PR TITLE
Completed Task 849 : Design System > Element > Progress Bar > Default : Enhancements in style

### LINKED ISSUE #849: Design System > Element > Progress Bar > Default  : Enhancements in style
Design System > Element > Progress Bar > Default  : Enhancements in style

### PR DESCRIPTION
**Pull request by rahulp34**
## Description
1] update the style of the default single progress bar, 
2] percentage shifted to right hand side of progress bar as per wireframe

image
image

Fixes # (issue)

> New style for default state implement as per wireframe

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
Please add screen snap

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
colorVariant changes are not  working

**Comment by rahulp34** [comment]
Colovariant list also updated from colorvariant.ts file. now we can see two colors only that is primary and error
image
image

**Review by hemalatagaikwad — APPROVED** [review]
review and approve

**Pull request merged**
