### PR TITLE
Completed Design System > Element or Component > Comment component issue while exporting it as a reference in another project and has formatting issue

### LINKED ISSUE #1107: Design System > Components > Chat > Default > Placeholder text & icon is not centralized.
**Describe the bug**
1. Chat > Default > Placeholder text & icon is not centralized.
2. Cookies Section> Default > Accept button is not display proper.

**Steps to reproduce bug**
1. Go to 'https://stage-react.raaghu.ai/'
3. Navigate to 'Design System > Components > Chat > Default'

**Actual result-**
1. Chat > Default > Placeholder text & icon is not centralized.
2. Cookies Section> Default > Accept button is not display proper.

**Screenshots**
image
image

Expected result-
image

**Expected result-**
1. Chat > Default > Placeholder text & icon should be centralized.
2. Cookies Section> Default > Accept button should be display proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

### LINKED ISSUE #1155: Design System > Element or Component > Comment component issue while exporting it as a reference in another project and has formatting issue
Pooja Kulkarni, report issue related to 'Comment' component. When she is referencing it, she is not able to export and it has/causes format issue in the code structure.

image (6)
image (5)
image (4)

### PR DESCRIPTION
**Pull request by dhirajlaha**
## Description
- Changed the interface of the chat component for resolving the export issue for the Comment Component
- Made some changes on the Emoji Picker issue where after picking the emoji it was showing undefined in the text input

## Fixes
- #1155 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
input height not matches 
image

**Comment by dhirajlaha** [comment]
> input height not matches image

Added changes for the height issues
image

**Review by poojagurav21 — CHANGES_REQUESTED** [review]
alignment issue
image

**Comment by nitinsonawane123** [comment]
Resolved alignment issue 
image

**Review by poojagurav21 — CHANGES_REQUESTED** [review]
Resolve conflicts
image

**Comment by nitinsonawane123** [comment]
Resolved conflict

**Review by poojagurav21 — APPROVED** [review]

**Review by hemalatagaikwad — APPROVED** [review]
approve

**Pull request merged**
