### PR TITLE
Resolved Bug 973 : All charts height width not working

### LINKED ISSUE #973: Design System > All Charts > Height Width is not working.
**Describe the bug**
Check All Charts > Height Width is not working.

**Steps to reproduce bug**
1. Go to 'https://dev-react.raaghu.ai/ & https://stage-react.raaghu.ai/'
2. Navigate to 'Design System > All Charts'

**Actual result-**
Check All Charts > Height Width is not working.

**Screenshots**
image

**Expected result-**
Check All Charts > Height Width should be working proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

### PR DESCRIPTION
**Pull request by DeepashriDatar**
## Screenshots :

1. Pie Chart
image

2. Area Chart
image

3. Horizontal Bar Chart
image

4. Vertical Bar Chart 
image

5. Stacked Bar Chart
image

6. Performance Stacked Bar Chart
image

7. Bar Chart With Border Radius
image

8. Mixed Chart
image

9. Polar Area Chart
image

10. Radar Chart
image

11. Scatter Chart
image

12. Scatter Chart With Multiple Axis
image

13. Stacked Chart
image

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
please resolved conflicts

**Comment by DeepashriDatar** [comment]
conflicts resolved

**Review by poojagurav21 — CHANGES_REQUESTED** [review]
Build issue
image

**Comment by DeepashriDatar** [comment]
@poojagurav21 Resolved build issues

**Review by poojagurav21 — APPROVED** [review]

**Review by hemalatagaikwad — APPROVED** [review]

**Pull request merged**
