### PR TITLE
Completed Task 759 : Design System > Create new component for Chatbot

### LINKED ISSUE #759: Design System > Create new component for Chatbot
Design System > Create new component for Chatbot
image

### PR DESCRIPTION
**Pull request by suchithravipin1991**
## Description
To Implement chat component with customizable options .

chat

The above wireframe is the reference for creating the chat component. 
Customizable features:
1. Dateformat'
2. FileUpload (default false)
3. EmojiPicker(default false , Need implementation in the next stage)
4. UserMessage Delete option

## How Has This Been Tested?

DesignSystems > componets > Chat 
chatcomponent

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
Please refer Figma for background color
image
Also add screen snap of Figma

**Comment by suchithravipin1991** [comment]
@hemalatagaikwad  : Snap of figma
chat

Consider the content inside the comment tab only

**Review by poojagurav21 — CHANGES_REQUESTED** [review]
Resolve conflicts
image

**Comment by abhijeetjawale1** [comment]
image

Changes is already presented on dev site

**Pull request closed without merging**
