### PR TITLE
Completed Task 590 : Design System > Enhancement > Implement different types of Alerts (For property name changes & alignment changes)

### LINKED ISSUE #590: Design System > Implement different types of Alerts
1.Review existing Alerts in storybook
2.For non existing alerts, Add new element for different types of additional Alerts with reference of below link 
https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu-Design-System?node-id=605-9960

Image

### PR DESCRIPTION
**Pull request by DeepashriDatar**
## Description

> Alert > Controls > 
    1. Style - It is handled in story
    2. change icon - it is just 'Icon', if user doesn't provide any then it will not show the icon
    3. show title, Title - if user provide the title then only it will show
    4. show link- showing (earlier handled internally)
    5. show button - showing (earlier handled internally)
    6. Text is not center - done

## ScreenShot 

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by hemalatagaikwad — CHANGES_REQUESTED** [review]
Please resolved conflicts

**Comment by DeepashriDatar** [comment]
conflicts resolved

**Review by poojagurav21 — CHANGES_REQUESTED** [review]
Resolved build errors
Screenshot 2024-11-18 123415

**Comment by DeepashriDatar** [comment]
Build fixed

**Review by poojagurav21 — APPROVED** [review]

**Review by hemalatagaikwad — APPROVED** [review]
review and approve

**Pull request merged**
